name: wRelease

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and create archive
      run: pwsh ./tools/release.ps1
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: blessing-skin-server Artifact
        path: ./*.zip
